### PR TITLE
Fix deprecations when updating to S3.4, set req. services as public

### PR DESCRIPTION
**Pull request by ajtis**
I just set public=true to services that should be accessible.

### CODE REVIEW

**Comment by xabbuh** [comment]
I am :-1: on making these services public. Rather use proper dependency injection instead of fetching the services from the container (Symfony 3.4 will show you nice deprecation messages).

**Comment by XWB** [comment]
This bundle fetches services from the container, some rewrite of the code is required.

**Comment by raziel057** [comment]
For me this PR must be merged to be able to migrate projects suing Assetic on Symfony 4 without having to replace Assetic with Webpack (as a first step). Currently it's just not possible...

**Comment by XWB** [comment]
@raziel057 Unfortunately we will have to accept that `assetic-bundle` has been abandoned.

**Comment by raziel057** [comment]
@XWB I understand it's not maintained anymore but

**Comment by COil** [comment]
Hello, I am currently fixing deprecations on a Symfony 3.4 project and those assetic are the last ones. to get this project deprecations free. 

    115x: The "assetic.filter.compass" service is private
    69x: The "assetic.filter.jpegoptim" service is private
    23x: The "assetic.filter_manager" service is private

Is there something that would prevent assetic to work with Symfony 4 ?

Our goal is like @raziel057 , we want to migrate the sooner possible to Symfony4 and then to remove assetic in flavor of webpack encore.

**Comment by COil** [comment]
Tested the pr and it works:

    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/COil/assetic-bundle"
        }
    ],
    "require": {
        ...
        "symfony/assetic-bundle": "3.0.0 as 2.8.3",

**Comment by COil** [comment]
BTW, even there is not more deprecation warning, the upgrade to sf4 won't work because of the dependencies:

     "symfony/framework-bundle": "~2.3|~3.0",
      "symfony/dependency-injection": "~2.3|~3.0",
      "symfony/console": "~2.3|~3.0",
     "symfony/yaml": "~2.3|~3.0",

**Pull request closed without merging**
