### PR TITLE
Remove usage of addClassesToCompile on PHP7+

### PR DESCRIPTION
**Pull request by acrobat**

### CODE REVIEW

**Comment by hjanuschka** [comment]
any chances this is going to be merged?

**Comment by stof** [comment]
I would remove the call entirely instead.

**Comment by acrobat** [comment]
Ok for me! I just did it the same way as it was done on the other bundles (framework, monolog, etc)

**Comment by acrobat** [comment]
@stof as you asked I've removed the usage of the method completely!

**Comment by nisanov** [comment]
Backwards compatibility?
```php
if (PHP_VERSION_ID < 70000) {
    'Symfony\\Bundle\\AsseticBundle\\DefaultValueSupplier',
    'Symfony\\Bundle\\AsseticBundle\\Factory\\AssetFactory',
    /* This will introduce hard dependency on Twig
    'Assetic\\Extension\\Twig\\AsseticExtension',
    'Assetic\\Extension\\Twig\\ValueContainer',
    'Symfony\\Bundle\\AsseticBundle\\Twig\\AsseticExtension',
    */
}
```

**Comment by acrobat** [comment]
@nisanov that was what I had in mind (see first commit). @stof what is the reason to remove this whole block? And is it indeed not a bc break?

**Comment by curry684** [comment]
@acrobat BC is not an issue as it was always only a performance improvement. Removing the entire block may degrade performance on old PHP versions, but not change any behavior. And seriously, for 2 classes it's likely only occasionally measurable on PHP5 versions before OpCache became standard in PHP 5.5.

**Comment by acrobat** [comment]
Already clear! The PR is ready for merge!

**Comment by XWB** [comment]
:+1:

**Comment by sjadema** [comment]
Is there any progress on this issue?

**Comment by XWB** [comment]
Ping @stof ? :)

**Comment by XWB** [comment]
Ping @fabpot perhaps? :)

**Comment by netsuo** [comment]
Sorry adding to this @fabpot & @stof , but it would be great if assetic at least fix deprecations because some of my projects are 99% ready to upgrade to symfony 4, 1% remaining being Assetic.
I would like to stop using assetic but the projects are to big to do it and I will probably use webpack for new projects.

**Comment by deguif** [comment]
Any chance to get this merged ?

**Comment by fabpot** [comment]
Thank you @acrobat.

**Comment by deguif** [comment]
Thanks @fabpot for merging this one.

**Comment by netsuo** [comment]
Thanks a lot !

**Pull request closed without merging**
