### PR TITLE
call method setOptions in filter-configuration of lessphp

### PR DESCRIPTION
**Pull request by lduer**
I've added some configuration-options, to use the ``setOptions`` of the LessphpFilter (https://github.com/kriswallsmith/assetic/pull/704) in the global config.

example usage:

```
assetic:
    # ...
    filters:
        lessphp:
            options: 
                relativeUrls: false
            file: "%kernel.root_dir%/../vendor/less-php/less.php/lessc.inc.php"            

    # ...
```

### CODE REVIEW

**Comment by lduer** [comment]
is now merged in the assetic-repository :)

**Comment by stof** [comment]
why is there a merge commit in the history ?

**Comment by lduer** [comment]
Since the creation of this PR, some new functions have been added to the assetic-bundle. I wanted to use the latest code AND the updated code from my fork.

Is it a probem, regarding the merge of the original commit "f8d4bc8" ?

**Comment by stof** [comment]
you should rebase in such case, not add a merge commit in the feature branch (the issue being also that you don't use a feature branch)

**Comment by stof** [comment]
and tests are failing for this PR

**Comment by lduer** [comment]
ok, i see. i didn't considered that the changes in the fork have impacts on the PR
 
the original commit should be able to merge (https://github.com/symfony/assetic-bundle/compare/master...lduer:master). 

what actions do you suggest?

**Comment by rudzboy** [comment]
+1 Don't let this down ;)

**Comment by guillaumelecerf** [comment]
@lduer : I can handle recreating the PR so that it is mergeable by @stof

**Comment by guillaumelecerf** [comment]
See #391

**Comment by lduer** [comment]
implementation into clean repository in #408

**Pull request closed without merging**
