### PR TITLE
Added CleanCSS filter config

### PR DESCRIPTION
**Pull request by thetiby**
updated version of https://github.com/symfony/assetic-bundle/pull/327

### CODE REVIEW

**Comment by thetiby** [comment]
@stof this [has been merged](https://github.com/kriswallsmith/assetic/pull/761) in assetic

**Comment by xabbuh** [comment]
@thetiby You can better use the values directly in your service config instead of creating parameters for all of them.

**Comment by thetiby** [comment]
@xabbuh I created these as a convenient list of defaults which I think work as a good starting point. Do you think I should remove them?

**Comment by xabbuh** [comment]
No, but you can use them directly below when configuring the service. There is no need for the parameters.

**Comment by thetiby** [comment]
@stof would you rather I use the defaults directly as @xabbuh suggested?

If not, is there anything else you'd like to see in this PR before merging? Thanks.

**Comment by stof** [comment]
@xabbuh not using parameters would require changing the way the DI extension of the bundle works

**Comment by thetiby** [comment]
@stof sorry for being so persistent, but can you tell me what would you like to see in this PR in order to merge it?

**Comment by thetiby** [comment]
@stof can you merge this please? or let me know what should I do to make it merge-able, if it's not?

**Comment by gremo** [comment]
+1 please merge if possibile, this would be a better alternative than uglifycss.

**Comment by thetiby** [comment]
@stof bump? I'm *not* trying to be obstinate, I'd ping someone else about this in order not to bother you of I knew whom

**Comment by kriswallsmith** [comment]
Thank you @thetiby!

**Pull request merged**
